host = "0.0.0.0"
port = 8050
path = "/mcp"

sample_name = "2dpsk_crystals"
dwell_imaging = 0.05
dwell_line_scan = 0.2
xrf_on = true
preamp1_on = false
using_xrf_maps = false
xrf_elms = ["Pb_L"]
xrf_roi_num = 23
allowable_x_range = [2203, 3644]
allowable_y_range = [5595, 7195]
allowable_z_range = [-4.5, 10.0]
allowable_zp_range = [-157.0, -144.0]
allowable_energy_range = [10.0, 10.03]
plot_image_in_log_scale = false
show_colorbar_in_image = false
line_scan_return_gaussian_fit = false
scan_samy = true

[qserver]
control_addr = "tcp://127.0.0.1:60615"
info_addr = "tcp://127.0.0.1:60625"
user_group = "root"
timeout_s = 4000
acquire_image = "fly2d_scanrecord"
acquire_line_scan = "step1d_scanrecord"
move_sample = "move_sample"
move_zp_z = "move_zp_z"
get_save_data_path = "get_save_data_path"
get_current_mda_file = "get_current_mda_file"
