"""APS 2-ID-D MIC backend instrument adapter."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any
import logging

import numpy as np

from control_suite_mcp_aps_2idd.aps_tools import APSSetParameters, APSTwoIDDAcquireImage

logger = logging.getLogger(__name__)


def json_safe(value: Any) -> Any:
    """Convert common NumPy payload values into JSON-serializable objects.

    Parameters
    ----------
    value
        Value returned by the underlying instrument code.

    Returns
    -------
    Any
        JSON-serializable value.
    """
    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, list | tuple):
        return [json_safe(item) for item in value]
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    return value


@dataclass(frozen=True)
class APSTwoIDDConfig:
    """Configuration for the APS 2-ID-D MIC instrument adapter.

    Parameters
    ----------
    sample_name
        Sample name passed to the Bluesky scan plans.
    dwell_imaging
        Image dwell time in seconds.
    dwell_line_scan
        Line-scan dwell time in seconds.
    xrf_on
        Whether to collect XRF data.
    preamp1_on
        Whether to collect Preamp1 data.
    using_xrf_maps
        Whether the worker should call XRF-Maps for image processing.
    xrf_elms
        XRF element names used when exporting image products.
    xrf_roi_num
        ROI number used for line-scan plots.
    allowable_x_range
        Optional allowed x-center range in microns.
    allowable_y_range
        Optional allowed y-center range in microns.
    allowable_z_range
        Optional allowed zone-plate z range.
    plot_image_in_log_scale
        Whether image products should be plotted in log scale.
    show_colorbar_in_image
        Whether exported images should include a colorbar.
    line_scan_return_gaussian_fit
        Whether line scans should include Gaussian fit metadata.
    scan_samy
        Whether line scans are generated by moving the sample-y motor.
    """

    sample_name: str = "smp1"
    dwell_imaging: float = 0.05
    dwell_line_scan: float = 0.2
    xrf_on: bool = True
    preamp1_on: bool = False
    using_xrf_maps: bool = False
    xrf_elms: tuple[str, ...] = ("Cr",)
    xrf_roi_num: int = 16
    allowable_x_range: tuple[float, float] | None = None
    allowable_y_range: tuple[float, float] | None = None
    allowable_z_range: tuple[float, float] | None = None
    plot_image_in_log_scale: bool = False
    show_colorbar_in_image: bool = False
    line_scan_return_gaussian_fit: bool = False
    scan_samy: bool = True


class APSTwoIDDMICInstrument:
    """Backend adapter owning APS 2-ID-D MIC Bluesky tool instances."""

    writable_config_names = {
        "sample_name",
        "dwell_imaging",
        "dwell_line_scan",
        "xrf_on",
        "preamp1_on",
        "using_xrf_maps",
        "xrf_elms",
        "xrf_roi_num",
        "allowable_x_range",
        "allowable_y_range",
        "allowable_z_range",
        "plot_image_in_log_scale",
        "show_colorbar_in_image",
        "line_scan_return_gaussian_fit",
        "scan_samy",
    }

    def __init__(self, config: APSTwoIDDConfig | None = None) -> None:
        """Initialize the beamline control objects inside the worker process."""
        self.config = APSTwoIDDConfig() if config is None else config
        self.acquire_image_tool, self.param_tuning_tool = self.create_tools(self.config)

    def create_tools(self, config: APSTwoIDDConfig) -> tuple[APSTwoIDDAcquireImage, APSSetParameters]:
        """Create and wire local APS MIC tools to the 2-ID-D Bluesky environment.

        Parameters
        ----------
        config
            Instrument configuration.

        Returns
        -------
        tuple[APSTwoIDDAcquireImage, APSSetParameters]
            The acquisition tool and parameter tuning tool.

        Raises
        ------
        ImportError
            If the APS 2-ID-D control environment cannot be imported.
        """
        try:
            import bluesky.plan_stubs as bps
            from s2idd_uprobe.startup import RE, fly2d_scanrecord, oregistry, step1d_scanrecord
        except ImportError as exc:
            raise ImportError(
                "APS 2-ID-D Bluesky control initialization failed. Run the worker "
                "in the beamline environment where bluesky and s2idd_uprobe are importable."
            ) from exc

        acquisition_tool = APSTwoIDDAcquireImage(
            sample_name=config.sample_name,
            dwell_imaging=config.dwell_imaging,
            dwell_line_scan=config.dwell_line_scan,
            xrf_on=config.xrf_on,
            preamp1_on=config.preamp1_on,
            using_xrf_maps=config.using_xrf_maps,
            xrf_elms=config.xrf_elms,
            xrf_roi_num=config.xrf_roi_num,
            allowable_x_range=config.allowable_x_range,
            allowable_y_range=config.allowable_y_range,
            allowable_z_range=config.allowable_z_range,
            plot_image_in_log_scale=config.plot_image_in_log_scale,
            show_colorbar_in_image=config.show_colorbar_in_image,
            line_scan_return_gaussian_fit=config.line_scan_return_gaussian_fit,
            scan_samy=config.scan_samy,
        )
        acquisition_tool.RE = RE
        acquisition_tool.savedata = oregistry["savedata"]
        acquisition_tool.scan2d_plan = fly2d_scanrecord
        acquisition_tool.scan1d_plan = step1d_scanrecord
        acquisition_tool.samy_motor = oregistry["samy"]
        acquisition_tool.bps = bps

        parameter_tool = APSSetParameters(
            parameter_ranges=self.resolve_parameter_ranges(config.allowable_z_range)
        )
        parameter_tool.RE = RE
        parameter_tool.zp_z_motor = oregistry["zp_z"]
        parameter_tool.bps = bps
        parameter_tool.allowable_z_range = config.allowable_z_range
        return acquisition_tool, parameter_tool

    def resolve_parameter_ranges(
        self,
        allowable_z_range: tuple[float, float] | None,
    ) -> list[tuple[float, ...]]:
        """Return parameter ranges for zone-plate z tuning."""
        if allowable_z_range is None:
            return [(-200.0,), (-180.0,)]
        return [(float(allowable_z_range[0]),), (float(allowable_z_range[1]),)]

    def health(self) -> dict[str, str]:
        """Return worker health."""
        return {"status": "ok"}

    def get_state(self) -> dict[str, Any]:
        """Return current worker and tool state."""
        return json_safe(
            {
                "sample_name": self.acquire_image_tool.sample_name,
                "dwell_imaging": self.acquire_image_tool.dwell_imaging,
                "dwell_line_scan": self.acquire_image_tool.dwell_line_scan,
                "xrf_on": self.acquire_image_tool.xrf_on,
                "preamp1_on": self.acquire_image_tool.preamp1_on,
                "using_xrf_maps": self.acquire_image_tool.using_xrf_maps,
                "xrf_elms": self.acquire_image_tool.xrf_elms,
                "xrf_roi_num": self.acquire_image_tool.xrf_roi_num,
                "line_scan_return_gaussian_fit": (
                    self.acquire_image_tool.line_scan_return_gaussian_fit
                ),
                "counter_acquire_image": self.acquire_image_tool.counter_acquire_image,
                "image_acquisition_call_history": (
                    self.acquire_image_tool.image_acquisition_call_history
                ),
                "line_scan_call_history": self.acquire_image_tool.line_scan_call_history,
                "current_image_info": self.acquire_image_tool.get_current_image_info(),
                "previous_image_info": self.acquire_image_tool.get_previous_image_info(),
                "initial_image_info": self.acquire_image_tool.get_initial_image_info(),
            }
        )

    def set_config(self, name: str, value: Any) -> dict[str, Any]:
        """Set a writable acquisition configuration value.

        Parameters
        ----------
        name
            Configuration attribute name.
        value
            JSON-serializable value to assign.

        Returns
        -------
        dict[str, Any]
            Updated name and value.
        """
        if name not in self.writable_config_names:
            raise ValueError(f"Unsupported configuration attribute: {name}")
        if name == "xrf_elms":
            value = tuple(value)
        if name.endswith("_range") and value is not None:
            value = tuple(float(item) for item in value)
        setattr(self.acquire_image_tool, name, value)
        if name == "allowable_z_range":
            self.param_tuning_tool.allowable_z_range = value
            self.param_tuning_tool.parameter_ranges = self.resolve_parameter_ranges(value)
        if name == "line_scan_return_gaussian_fit":
            value = bool(value)
            self.acquire_image_tool.line_scan_return_gaussian_fit = value
        return {"name": name, "value": json_safe(value)}

    def set_attribute(self, name: str, value: Any) -> dict[str, Any]:
        """Alias for ``set_config`` used by the MCP acquisition proxy."""
        return self.set_config(name=name, value=value)

    def acquire_image(
        self,
        width: float,
        height: float,
        x_center: float,
        y_center: float,
        stepsize_x: float,
        stepsize_y: float,
    ) -> dict[str, Any]:
        """Acquire an APS MIC image using the MCP acquisition contract."""
        result = self.acquire_image_tool.acquire_image(
            width=width,
            height=height,
            x_center=x_center,
            y_center=y_center,
            stepsize_x=stepsize_x,
            stepsize_y=stepsize_y,
        )
        return json_safe(result)

    def acquire_line_scan(
        self,
        length: float,
        x_center: float,
        y_center: float,
        stepsize_x: float,
    ) -> dict[str, Any]:
        """Acquire an APS MIC line scan using the MCP acquisition contract."""
        result = self.acquire_image_tool.acquire_line_scan(
            length=length,
            x_center=x_center,
            y_center=y_center,
            stepsize_x=stepsize_x,
        )
        return json_safe(result)

    def set_parameters(self, parameters: list[float]) -> str:
        """Set beamline tuning parameters through the local parameter tool."""
        return self.param_tuning_tool.set_parameters(parameters=parameters)
